branch-defaults:
  deploy_beanstalk:
    environment: rpg-app-env
global:
  application_name: rtassignment
  default_ec2_keyname: null
  default_platform: Ruby 2.2 (Puma)
  default_region: us-west-2
  profile: eb-cli
  sc: git

container_commands:
  01_bundle:
    command: "bundle install"
